### ISSUE TITLE
An error while compiling JPScore under Ubuntu 12.04

### ISSUE THREAD

**Issue by drscopus** [JuPedSim/JuPedSim#4]
when I try to compile it by inputting "cmake CMakeList.txt" under the directory JPScore as the instruction says, a strange error comes out:
"/home/turtlebot/people2D_laser/JuPedSim/JPScore/routing/cognitive_map/CognitiveMapStorage.cpp: In member function 'void CognitiveMapStorage::CreateCognitiveMap(CMStorageKeyType)':
/home/turtlebot/people2D_laser/JuPedSim/JPScore/routing/cognitive_map/CognitiveMapStorage.cpp:64:21: error: 'CMStorageType' has no member named 'emplace'
make[2]: *** [CMakeFiles/core.dir/routing/cognitive_map/CognitiveMapStorage.cpp.o] Error 1
make[1]: *** [CMakeFiles/core.dir/all] Error 2
make: *** [all] Error 2
22:18:59: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project JPScore (kit: Desktop)
When executing step "Make"

I have no idea of solving it, because unordered_map has member the function "emplace" since c++11. My gcc is 4.6.3.

**Comment by piccolodream** [comment]
The compiler used should supper c++11.

**Comment by akfoss** [comment]
You may compile the latest GCC or use `Ubuntu Toolchain` PPA to install the latest GCC on your Ubuntu Precise.

    $ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    $ sudo apt-get update
    $ sudo apt-get install g++-4.9

After that, you may OPTIONALLY link `g++` to your newly installed compiler using

    $ update-alternatives --display g++
    $ sudo update-alternatives --remove-all g++
    $ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
    $ sudo update-alternatives --config g++
